### PR TITLE
Regex should be compiled

### PR DESCRIPTION
**Pull request by akeeman**

### CODE REVIEW

**Comment by matthiask** [comment]
Thanks!

Do you want to try adding a test too to verify that this doesn't regress? It seems that test coverage is lacking otherwise this wouldn't have happened in the first place.

**Comment by matthiask** [comment]
On second thought it would be better to follow `normalize_overall_whitespace` here and use `re.sub` instead. https://github.com/matthiask/html-sanitizer/blob/2c17162481e59b9e3ba8ac9a9df449866f6dc9e1/html_sanitizer/sanitizer.py#L61

I'm not sure but I think that the `re` module keeps compiled versions of regexes around (in a LRU cache) and does not always recompile them.

**Comment by akeeman** [comment]
I actually doubt whether this is in a valid execution path at all, so if you treat the regex parameter as required you can just remove the `if` block here. I didn't actually bump into .sub being called on a string, I just noticed this while looking for a way to disable whitespace adjustments at all (which turns out not to be available easily).

**Comment by matthiask** [comment]
It seems to be possible to override the `whitespace_re` attribute on the `Sanitizer` instance and by doing that you could disable some of the whitespace normalization. I'm not completely sure though since I never customize the whitespace normalization at all (changes were introduced in #14 )

I agree with making more arguments required. This also helps with code coverage.

**Pull request merged**
